import { IconDefinition, IconPack, IconPrefix } from '@fortawesome/fontawesome-common-types';

export { IconDefinition, IconPack, IconPrefix } from '@fortawesome/fontawesome-common-types';
export const odAdjust: IconDefinition;
export const odBack: IconDefinition;
export const odCancelsmall: IconDefinition;
export const odCancel: IconDefinition;
export const odCheckmark: IconDefinition;
export const odConfirmsmall: IconDefinition;
export const odConnect: IconDefinition;
export const odControl: IconDefinition;
export const odDelete: IconDefinition;
export const odError: IconDefinition;
export const odFan: IconDefinition;
export const odFilament: IconDefinition;
export const odFolder: IconDefinition;
export const odHeatbed: IconDefinition;
export const odHeat: IconDefinition;
export const odHeight: IconDefinition;
export const odHelp: IconDefinition;
export const odInvalidconfig: IconDefinition;
export const odNext: IconDefinition;
export const odNozzle: IconDefinition;
export const odObject: IconDefinition;
export const odPause: IconDefinition;
export const odPrint: IconDefinition;
export const odResume: IconDefinition;
export const odSettings: IconDefinition;
export const odSort: IconDefinition;
export const odThermometer: IconDefinition;
export const odUpload: IconDefinition;
export const prefix: IconPrefix;
export const od: IconPack;
